export interface DiagnosisEntry {
  id: string;
  symptom: string;
  cause: string;
  advice: string;
  category: "mangel" | "schaedling" | "krankheit" | "sonstiges";
  image?: string; // path under /public
}

export const DIAGNOSIS_ENTRIES: DiagnosisEntry[] = [
  // ─── Nährstoffmängel (Mangel) ────────────────────────────────────────────
  {
    id: "eagle-claws",
    symptom: "Adlerkrallen (Blätter krallen sich nach unten)",
    cause: "Überdüngung (zu viel N)",
    advice: "EC senken, ggf. mit klarem Wasser (pH 6,0–6,5) durchspülen.",
    category: "mangel",
    image: "diagnosis/eagle-claws.jpg",
  },
  {
    id: "n-deficiency",
    symptom: "Gleichmäßig gelb, von alten zu neuen Blättern",
    cause: "Stickstoff(N)-Mangel oder pH zu hoch",
    advice: "Erst pH prüfen (Ziel 6,0–6,5), dann ggf. N-Dünger leicht erhöhen.",
    category: "mangel",
    image: "diagnosis/n-deficiency.jpg",
  },
  {
    id: "p-deficiency",
    symptom: "Lila/violette Stängel und Blattadern",
    cause: "Phosphor(P)-Mangel oder Kälte (<15°C)",
    advice: "Temperatur prüfen, bei Bedarf P-Dünger (z.B. PK 13-14) anpassen.",
    category: "mangel",
    image: "diagnosis/p-deficiency.jpg",
  },
  {
    id: "k-deficiency",
    symptom: "Braune, verbrannte Blattränder",
    cause: "Kalium(K)-Mangel oder Hitzeschaden",
    advice: "Abstand zur Lampe prüfen, K-Dünger nach Wochenplan anpassen.",
    category: "mangel",
    image: "diagnosis/k-deficiency.jpg",
  },
  {
    id: "mg-deficiency",
    symptom: "Fenster-Muster (Adern grün, Fläche vergilbt)",
    cause: "Magnesium(Mg)-Mangel",
    advice: "Bittersalz-Spray (Epsom-Salz, ca. 1 TL/L) oder Calmag ins Gießwasser.",
    category: "mangel",
    image: "diagnosis/mg-deficiency.jpg",
  },
  {
    id: "ca-deficiency",
    symptom: "Braune, eingedrückte Flecken an neuen Blättern / verkrüppelte Spitzen",
    cause: "Calcium(Ca)-Mangel, oft bei zu schnellem Wachstum",
    advice: "Calmag-Dünger zugeben, Luftfeuchtigkeit kontrollieren (Ca-Aufnahme braucht stabile RH).",
    category: "mangel",
    image: "diagnosis/ca-deficiency.jpg",
  },
  {
    id: "s-deficiency",
    symptom: "Jüngere Blätter hellgrün bis gelb, Adern oft heller",
    cause: "Schwefel(S)-Mangel (selten, ähnlich N-Mangel)",
    advice: "Volldünger mit S-Anteil verwenden, pH prüfen (S wird bei hohem pH schlecht aufgenommen).",
    category: "mangel",
    image: "diagnosis/s-deficiency.jpg",
  },
  {
    id: "fe-deficiency",
    symptom: "Neue Blätter leuchtend gelb / fast weiß, Adern oft noch grün",
    cause: "Eisen(Fe)-Mangel, meist durch zu hohen pH ausgelöst",
    advice: "pH-Wert senken (Richtung 6,0), Eisen wird bei zu hohem pH nicht aufgenommen.",
    category: "mangel",
    image: "diagnosis/fe-deficiency.jpg",
  },
  {
    id: "zn-deficiency",
    symptom: "Kleine, schmale neue Blätter, gestauchte Triebe",
    cause: "Zink(Zn)-Mangel oder pH zu hoch",
    advice: "pH Richtung 6,0 bringen, ggf. Zn-haltigen Mikronährstoff-Mix verwenden.",
    category: "mangel",
    image: "diagnosis/zn-deficiency.jpg",
  },
  {
    id: "mn-deficiency",
    symptom: "Neue Blätter gelb mit grünen Adern, teils braune Punkte",
    cause: "Mangan(Mn)-Mangel, ähnlich Fe-Mangel",
    advice: "pH prüfen, Mikronährstoff-Dünger beimischen.",
    category: "mangel",
    image: "diagnosis/mn-deficiency.jpg",
  },
  {
    id: "b-deficiency",
    symptom: "Verdickte, brüchige neue Triebe, hohle Stängel",
    cause: "Bor(B)-Mangel (selten)",
    advice: "Bor-haltigen Dünger in sehr kleiner Dosis zugeben (B-Überdüngung ist kritisch!).",
    category: "mangel",
    image: "diagnosis/b-deficiency.jpg",
  },
  {
    id: "cu-deficiency",
    symptom: "Neue Triebe welken, blau-grüne Verfärbung",
    cause: "Kupfer(Cu)-Mangel (sehr selten)",
    advice: "pH prüfen, Mikronährstoff-Mix verwenden.",
    category: "mangel",
    image: "diagnosis/cu-deficiency.jpg",
  },
  {
    id: "light-burn",
    symptom: "Obere Blätter gelb/weiß ausgebleicht, zur Lampe hin",
    cause: "Lichtverbrennung (zu nah oder zu stark)",
    advice: "Abstand zur Lampe vergrößern, ggf. Dimmen, PPFD mit Messgerät kontrollieren.",
    category: "mangel",
    image: "diagnosis/light-burn.jpg",
  },
  {
    id: "overwatering",
    symptom: "Schlaffe, hängende Blätter trotz feuchter Erde",
    cause: "Überwässerung → Wurzeln ersticken",
    advice: "Gießabstand verlängern, Erde abtrocknen lassen, Drainage prüfen.",
    category: "mangel",
    image: "diagnosis/overwatering.jpg",
  },
  {
    id: "underwatering",
    symptom: "Schlaffe, hängende Blätter, trockener Topf",
    cause: "Unterwässerung / ausgetrockneter Wurzelballen",
    advice: "Langsam wieder anfeuchten, evtl. Topf 10 Min in Wasser stellen.",
    category: "mangel",
    image: "diagnosis/underwatering.jpg",
  },

  // ─── Krankheiten & Pilze ─────────────────────────────────────────────────
  {
    id: "root-rot",
    symptom: "Pflanze welk trotz feuchter Erde, braune matschige Wurzeln",
    cause: "Wurzelfäule (z.B. Pythium)",
    advice: "Zwischen den Gießgängen abtrocknen lassen, Perlite beimischen, ggf. H2O2 3% (10ml/L) ins Gießwasser.",
    category: "krankheit",
    image: "diagnosis/root-rot.jpg",
  },
  {
    id: "botrytis",
    symptom: "Grauer, wattiger Belag im Bud",
    cause: "Botrytis (Grauschimmel)",
    advice: "Befallene Stellen sofort mit Handschuhen entfernen und entsorgen, Luftfeuchtigkeit in der Spätblüte auf 40–50% senken, Luftzirkulation verbessern.",
    category: "krankheit",
    image: "diagnosis/botrytis.jpg",
  },
  {
    id: "powdery-mildew",
    symptom: "Weißer, puderartiger Belag auf Blättern",
    cause: "Echter Mehltau",
    advice: "Backpulver-Spray (5g + 1ml Spülmittel/L) oder Milch-Spray (30% Milch/70% Wasser), Luftzirkulation erhöhen.",
    category: "krankheit",
    image: "diagnosis/powdery-mildew.jpg",
  },
  {
    id: "damping-off",
    symptom: "Sämlinge kippen um, Stängel am Boden eingeschnürt",
    cause: "Umfallkrankheit (Pythium / Rhizoctonia)",
    advice: "Substrat sterilisieren, weniger gießen, Lüftung erhöhen, Zimt als Hausmittel aufstreuen.",
    category: "krankheit",
    image: "diagnosis/damping-off.jpg",
  },
  {
    id: "fusarium",
    symptom: "Einseitig welkende Triebe, braune Verfärbung im Stängel",
    cause: "Fusarium-Welke",
    advice: "Befallene Pflanzen entsorgen, Werkzeuge desinfizieren, Substrat wechseln.",
    category: "krankheit",
    image: "diagnosis/fusarium.jpg",
  },
  {
    id: "septoria",
    symptom: "Viele kleine braune Flecken mit dunklem Rand auf Blättern",
    cause: "Septoria-Blattfleckenkrankheit",
    advice: "Befallene Blätter entfernen, Luftfeuchte senken, Neem-Öl sprühen.",
    category: "krankheit",
    image: "diagnosis/septoria.jpg",
  },
  {
    id: "rust",
    symptom: "Orange/braune Pusteln auf Blattunterseiten",
    cause: "Rostpilz",
    advice: "Befallene Blätter entfernen, Pflanze isolieren, Fungizid auf Schwefelbasis einsetzen.",
    category: "krankheit",
    image: "diagnosis/rust.jpg",
  },
  {
    id: "bud-rot",
    symptom: "Braune, matschige Stellen von innen im Bud",
    cause: "Bud Rot (Grauschimmel im Bud)",
    advice: "Befallene Buds großzügig abschneiden, RH unter 50% halten, Luftzirkulation verbessern.",
    category: "krankheit",
    image: "diagnosis/bud-rot.jpg",
  },

  // ─── Schädlinge ──────────────────────────────────────────────────────────
  {
    id: "spider-mites",
    symptom: "Feine helle Sprenkel auf Blättern + feine Gespinste",
    cause: "Spinnmilben",
    advice: "Luftfeuchtigkeit über 50% halten, Neem-Öl (3ml + 1ml Spülmittel/L) alle 3 Tage, alternativ Raubmilben einsetzen.",
    category: "schaedling",
    image: "diagnosis/spider-mites.jpg",
  },
  {
    id: "fungus-gnats",
    symptom: "Kleine schwarze Fliegen um den Topf",
    cause: "Trauermücken",
    advice: "Erdoberfläche zwischen den Gießgängen abtrocknen lassen, Nematoden (Steinernema feltiae) ins Gießwasser geben.",
    category: "schaedling",
    image: "diagnosis/fungus-gnats.jpg",
  },
  {
    id: "thrips",
    symptom: "Silbrige, gesprenkelte Blätter + kleine schwarze Kotpunkte",
    cause: "Thripse",
    advice: "Blau-staue Leimtafeln, Neem-Öl oder Raubmilben (A. cucumeris). Befallene Blätter entfernen.",
    category: "schaedling",
    image: "diagnosis/thrips.jpg",
  },
  {
    id: "aphids",
    symptom: "Kleine grüne/schwarze Insekten an Triebspitzen, klebrige Beläge",
    cause: "Blattläuse",
    advice: "Mit Wasser abspülen, Neem-Öl sprühen, Marienkäfer/Larven als Nützlinge einsetzen.",
    category: "schaedling",
    image: "diagnosis/aphids.jpg",
  },
  {
    id: "whiteflies",
    symptom: "Weiße, kleine fliegende Insekten bei Berührung der Pflanze",
    cause: "Weiße Fliege",
    advice: "Gelbsticker aufhängen, Neem-Öl sprühen, Schlupfwespen (Encarsia formosa) einsetzen.",
    category: "schaedling",
    image: "diagnosis/whiteflies.jpg",
  },
  {
    id: "mealybugs",
    symptom: "Weiße, watteähnliche Beläge in Blattachseln und an Stängeln",
    cause: "Wollläuse",
    advice: "Mit Q-Tip in Alkohol (70%) betupfen, Neem-Öl sprühen, Pflanze isolieren.",
    category: "schaedling",
    image: "diagnosis/mealybugs.jpg",
  },
  {
    id: "scale",
    symptom: "Bräunliche, höckerartige Beläge an Stängeln, klebrige Blätter",
    cause: "Schildläuse",
    advice: "Mit Alkohol/Q-Tip mechanisch entfernen, Neem-Öl sprühen.",
    category: "schaedling",
    image: "diagnosis/scale.jpg",
  },
  {
    id: "caterpillars",
    symptom: "Angefressene Blattränder, kleine dunkle Kotkrümel",
    cause: "Raupen (z.B. Eulenfalter-Larven)",
    advice: "Bt (Bacillus thuringiensis) sprühen, Pflanzen abends kontrollieren und Raupen absammeln.",
    category: "schaedling",
    image: "diagnosis/caterpillars.jpg",
  },
  {
    id: "leaf-miners",
    symptom: "Weiße, geschlängelte Linien/Gänge im Blatt",
    cause: "Minierfliegen",
    advice: "Befallene Blätter entfernen, Gelbtafeln, Neem-Öl.",
    category: "schaedling",
    image: "diagnosis/leaf-miners.jpg",
  },
  {
    id: "springtails",
    symptom: "Kleine weiße/springende Tierchen auf feuchter Erde",
    cause: "Springschwänze (meist harmlos, Zeichen für zu nasse Erde)",
    advice: "Erde abtrocknen lassen, ggf. Deckschicht aus Sand/Hydrokugeln, an sich kein Schaden.",
    category: "schaedling",
    image: "diagnosis/springtails.jpg",
  },

  // ─── Sonstiges (Umwelt, Stress) ───────────────────────────────────────────
  {
    id: "heat-stress",
    symptom: "Blattränder nach oben eingerollt (Bonnet), sehr hohe Temp.",
    cause: "Hitzestress (>30°C Blatt-Temp.)",
    advice: "Abluft/Umluft erhöhen, ggf. Klimaanlage, Abstand zur Lampe vergrößern.",
    category: "sonstiges",
    image: "diagnosis/heat-stress.jpg",
  },
  {
    id: "cold-stress",
    symptom: "Lila Verfärbungen, langsames Wachstum",
    cause: "Kältestress (<15°C Wurzel-Temp.)",
    advice: "Heizmatte, Wurzelzone warm halten, evtl. auf Outdoor-Standort prüfen.",
    category: "sonstiges",
    image: "diagnosis/cold-stress.jpg",
  },
  {
    id: "low-humidity",
    symptom: "Braune, knusprige Blattränder, Blätter rollen sich ein",
    cause: "Zu niedrige Luftfeuchtigkeit (<35%)",
    advice: "Luftbefeuchter einsetzen, Schalen mit Wasser aufstellen.",
    category: "sonstiges",
    image: "diagnosis/low-humidity.jpg",
  },
  {
    id: "high-humidity",
    symptom: "Kondenswasser an Blättern, schimmelige Stellen",
    cause: "Zu hohe Luftfeuchtigkeit (>70% in der Blüte)",
    advice: "Lüftung/Umluft erhöhen, Entfeuchter, Wasserquellen reduzieren.",
    category: "sonstiges",
    image: "diagnosis/high-humidity.jpg",
  },
  {
    id: "ph-drift",
    symptom: "Generell schlechtes Wachstum, viele Mini-Mängel gleichzeitig",
    cause: "pH-Wert nicht im Zielbereich (5,8–6,5)",
    advice: "pH jeder Gieß- und Düngerlösung messen und auf 6,0–6,2 einstellen.",
    category: "sonstiges",
    image: "diagnosis/ph-drift.jpg",
  },
  {
    id: "rootbound",
    symptom: "Wurzeln wachsen aus dem Topf, schnelles Austrocknen, Wachstumsstopp",
    cause: "Topf zu klein (rootbound)",
    advice: "Umtopfen in größeren Topf (Faustregel: max. 1/3 größeres Volumen pro Schritt).",
    category: "sonstiges",
    image: "diagnosis/rootbound.jpg",
  },
  {
    id: "light-stress",
    symptom: "Blätter bleichen aus, gelbe Spitzen ohne Mangel",
    cause: "Zu viel Licht (PPFD über Limit der Sorte)",
    advice: "Lampe höher hängen oder dimmen, an Genetik anpassen (Sativa verträgt mehr als Indica).",
    category: "sonstiges",
    image: "diagnosis/light-stress.jpg",
  },
  {
    id: "leggy-seedling",
    symptom: "Sämling wächst lang und dünn in die Höhe",
    cause: "Zu wenig Licht oder zu viel Wärme in Keimphase",
    advice: "Lampe näher und weniger hell (z.B. 18/6) oder kühler stellen, ggf. tiefer einsetzen.",
    category: "sonstiges",
    image: "diagnosis/leggy-seedling.jpg",
  },
  {
    id: "hermaphrodite",
    symptom: "Pflanze bildet sowohl Blüten als auch Pollensäcke (Bananen)",
    cause: "Stress-Hermaphroditismus (Licht, Hitze, Beschädigung)",
    advice: "Stress reduzieren, einzelne Pollen-Säcke mit Pinzette entfernen, ggf. Pflanze opfern (Samen unerwünscht).",
    category: "sonstiges",
    image: "diagnosis/hermaphrodite.jpg",
  },
  {
    id: "nutrient-lockout",
    symptom: "Mangelerscheinungen trotz regelmäßigem Düngen",
    cause: "Nährstoff-Lockout (falscher pH oder Salz-Aufbau)",
    advice: "pH prüfen, mit 3-fachem Topfvolumen pH-korrigiertem Wasser durchspülen (Flushing).",
    category: "sonstiges",
    image: "diagnosis/nutrient-lockout.jpg",
  },
];

export const DIAGNOSIS_CATEGORY_LABELS: Record<DiagnosisEntry["category"], string> = {
  mangel: "🍂 Nährstoffmangel & Stress",
  schaedling: "🐛 Schädlinge",
  krankheit: "🦠 Krankheiten & Pilze",
  sonstiges: "❓ Sonstiges",
};
