import type { Strain } from "./types";

/**
 * Umfangreiche Strain-Datenbank mit bekannten Sorten.
 * Daten basierend auf öffentlich verfügbaren Informationen
 * (Seedfinder, StrainElite, StrainCompass, Leafly, etc.)
 */
export const SEED_STRAINS: Omit<Strain, "id" | "createdAt">[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // INDICA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Northern Lights",
    type: "indica",
    genetics: "90% Indica / 10% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "16–21%",
    cbd: "<1%",
    description: "Legendäre Indica aus den 70ern, entwickelt in Seattle und verfeinert in den Niederlanden. Eine der meistgepreissten Sorten aller Zeiten. Extrem robust, schimmelresistent und anfängerfreundlich.",
    aroma: "Süß, pine, leicht würzig",
    effect: "Stark entspannend, körperlich, schlaffördernd",
  },
  {
    name: "Hindu Kush",
    type: "indica",
    genetics: "100% Indica",
    plantType: "photo",
    floweringDays: 49,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–25%",
    cbd: "<1%",
    description: "Reine Landrasse aus dem Hindu-Kush-Gebirge zwischen Afghanistan und Pakistan. Seit Jahrhunderten kultiviert. Kompakte, harzige Buds.",
    aroma: "Erdig, süß, sandelholzartig",
    effect: "Tief entspannend, sedierend, körperlich",
  },
  {
    name: "Afghani",
    type: "indica",
    genetics: "100% Indica",
    plantType: "photo",
    floweringDays: 45,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "18–28%",
    cbd: "<1%",
    description: "Klassische afghanische Landrasse. Kurze, buschige Pflanze mit extrem harzigen Buds. Ideal für Haschisch-Produktion.",
    aroma: "Erdig, süß, pine",
    effect: "Stark sedierend, entspannend, couch-lock",
  },
  {
    name: "Bubba Kush",
    type: "indica",
    genetics: "100% Indica",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–23%",
    cbd: "<1%",
    description: "Berühmte Indica aus Kalifornien. Schwere, dichte Buds mit extrem starkem Effekt. Eine der schwersten Indicas auf dem Markt.",
    aroma: "Süß, erdig, kaffeeartig",
    effect: "Stark sedierend, couch-lock, schlaffördernd",
  },
  {
    name: "Granddaddy Purple",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "17–27%",
    cbd: "<1%",
    description: "Wunderschöne lila Buds, entstanden aus Purple Urkle. Bekannt für ihr beeriges Aroma und starken Indica-Effekt.",
    aroma: "Traube, Beeren, süß",
    effect: "Entspannend, euphorisch, sedierend",
  },
  {
    name: "Purple Punch",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "photo",
    floweringDays: 56,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Kreuzung aus Larry OG und Purple Diesel. Wunderschöne lila Buds mit intensivem Beerengeschmack.",
    aroma: "Traube, Blaubeere, Traubensaft",
    effect: "Entspannend, euphorisch, körperlich",
  },
  {
    name: "Critical Kush",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "20–24%",
    cbd: "<1%",
    description: "Kreuzung aus Critical Mass und OG Kush. Schnelle, robuste Indica mit kurzen Blütezeit. Ideal für Einsteiger.",
    aroma: "Erdig, pine, süß",
    effect: "Tief entspannend, körperlich, beruhigend",
  },
  {
    name: "Critical Mass",
    type: "indica",
    genetics: "65% Indica / 35% Sativa",
    plantType: "photo",
    floweringDays: 49,
    difficulty: "leicht",
    yieldIndoor: "500–600g/m²",
    thc: "18–22%",
    cbd: "1–2%",
    description: "Skunk #1 x Afghani. Bekannt für extrem hohe Erträge und kurze Blütezeit. Die Buds werden so schwer, dass sie Support brauchen.",
    aroma: "Süß, erdig, skunk",
    effect: "Entspannend, körperlich, mild",
  },
  {
    name: "LA Confidential",
    type: "indica",
    genetics: "75% Indica / 25% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Afghani x LA Affie. Eine der potentesten Indicas aus Los Angeles. Dichte, harzige Buds.",
    aroma: "Pine, erdig, leicht blumig",
    effect: "Stark entspannend, sedierend, körperlich",
  },
  {
    name: "God Bud",
    type: "indica",
    genetics: "90% Indica / 10% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "Kanadische Indica-Legende. Sehr harzreich, kompakte Buds. Benannt wegen ihres fast spirituellen Effekts.",
    aroma: "Süß, blumig, erdig",
    effect: "Stark entspannend, meditativ, körperlich",
  },
  {
    name: "Pink Panties",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "22–28%",
    cbd: "<1%",
    description: "Burmese Kush x Purple Purps. Extrem potent und harzreich. Eine versteckte Perle der Indica-Welt.",
    aroma: "Erdig, pine, blumig",
    effect: "Stark sedierend, körperlich, euphorisch",
  },
  {
    name: "Black Domina",
    type: "indica",
    genetics: "95% Indica / 5% Sativa",
    plantType: "photo",
    floweringDays: 45,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Ortega x Northern Lights x Hash Plant x Mass Super Skunk. Eine der reinsten Indicas. Schnell in der Blüte, extrem kompakt.",
    aroma: "Erdig, süß, leicht würzig",
    effect: "Stark sedierend, körperlich, entspannend",
  },
  {
    name: "Ice Cream",
    type: "indica",
    genetics: "75% Indica / 25% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Gelato-Familie mit cremigem Aroma. Dichte Buds mit einem Hauch von Lila. Beliebte Dessert-Sorte.",
    aroma: "Cremig, süß, vanilleartig",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "Do-Si-Dos",
    type: "indica",
    genetics: "70% Indica / 30% Sativa",
    plantType: "photo",
    floweringDays: 56,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–28%",
    cbd: "<1%",
    description: "Girl Scout Cookies x Face Off OG. Eine der stärksten modernen Indicas. Wunderschöne lila-grüne Buds.",
    aroma: "Süß, erdig, blumig",
    effect: "Stark entspannend, sedierend, euphorisch",
  },
  {
    name: "Animal Cookies",
    type: "indica",
    genetics: "70% Indica / 30% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "Fire OG x GSC (Girl Scout Cookies). Extrem potent mit komplexem Terpenprofil. Eine Premium-Sorte.",
    aroma: "Süß, nussig, erdig",
    effect: "Entspannend, euphorisch, hungeranregend",
  },
  {
    name: "GMO (Garlic Mushroom Onion)",
    type: "indica",
    genetics: "70% Indica / 30% Sativa",
    plantType: "photo",
    floweringDays: 65,
    difficulty: "schwer",
    yieldIndoor: "350–450g/m²",
    thc: "22–30%",
    cbd: "<1%",
    description: "Chemdog x Girl Scout Cookies. Berüchtigt für ihr intensives Knoblauch-Aroma. Nichts für schwache Nerven – eine der stärksten Sorten.",
    aroma: "Knoblauch, Zwiebel, erdig",
    effect: "Stark sedierend, körperlich, intensiv",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // SATIVA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Amnesia Haze",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "photo",
    floweringDays: 80,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Preisgekrönter Sativa-dominanter Hybrid (Cannabis Cup Gewinner). Braucht länger in der Blüte, lohnt sich aber mit erstklassigem High.",
    aroma: "Citrus, erdig, scharf",
    effect: "Euphorisch, energiegeladen, kreativ",
  },
  {
    name: "Jack Herer",
    type: "sativa",
    genetics: "55% Sativa / 45% Indica",
    plantType: "photo",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "18–23%",
    cbd: "<1%",
    description: "Benannt nach dem Cannabis-Aktivisten und Autor. Haze x Northern Lights #5 x Shiva Skunk. Klares, kreatives High.",
    aroma: "Würzig, pine, citrus",
    effect: "Klar, kreativ, euphorisch",
  },
  {
    name: "Sour Diesel",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "photo",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "Legendäre NYC-Sorte. Super Lemon x Chemdog 91. Das 'Diesel'-Aroma ist unverkennbar. Eine der beliebtesten Sativas weltweit.",
    aroma: "Diesel, chemisch, citrus",
    effect: "Energisch, euphorisch, fokussierend",
  },
  {
    name: "Durban Poison",
    type: "sativa",
    genetics: "100% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "18–25%",
    cbd: "<1%",
    description: "Reine südafrikanische Landrasse aus Durban. Eine der wenigen echten reinen Sativas. Süßes, erdiges Terpenprofil.",
    aroma: "Süß, erdig, pine, anis",
    effect: "Energisch, klar, kreativ, motivierend",
  },
  {
    name: "Super Lemon Haze",
    type: "sativa",
    genetics: "80% Sativa / 20% Indica",
    plantType: "photo",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Lemon Skunk x Super Silver Haze. Mehrfacher Cannabis Cup Gewinner. Intensives Zitronen-Aroma.",
    aroma: "Zitrone, citrus, süß",
    effect: "Energisch, euphorisch, kreativ",
  },
  {
    name: "Green Crack",
    type: "sativa",
    genetics: "80% Sativa / 20% Indica",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Skunk #1 x Afghani. Trotz des umstrittenen Namens eine der beliebtesten Tages-Sorten. Scharfes, süßes Aroma.",
    aroma: "Süß, mango, citrus, erdig",
    effect: "Energisch, fokussierend, glücklich",
  },
  {
    name: "Tangie",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "photo",
    floweringDays: 63,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "19–26%",
    cbd: "<1%",
    description: "New York City x Tangerine. Extrem oranges Terpenprofil. Mehrfacher Cup-Gewinner.",
    aroma: "Orange, citrus, süß",
    effect: "Energisch, euphorisch, kreativ",
  },
  {
    name: "Haze",
    type: "sativa",
    genetics: "90% Sativa / 10% Indica",
    plantType: "photo",
    floweringDays: 90,
    difficulty: "schwer",
    yieldIndoor: "300–400g/m²",
    thc: "15–21%",
    cbd: "<1%",
    description: "Die Ur-Mutter aller Haze-Sorten. Ursprünglich aus den 60ern/70ern. Lange Blütezeit, aber einzigartiges High.",
    aroma: "Würzig, erdig, citrus",
    effect: "Klar, psychedelisch, kreativ, langanhaltend",
  },
  {
    name: "Strawberry Cough",
    type: "sativa",
    genetics: "80% Sativa / 20% Indica",
    plantType: "photo",
    floweringDays: 63,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Haze x Strawberry. Berühmt für ihr intensives Erdbeer-Aroma und das 'Husten'-Phänomen beim Rauchen. Anfängerfreundlich.",
    aroma: "Erdbeere, süß, beerig",
    effect: "Euphorisch, sozial, angstlösend",
  },
  {
    name: "Ace Seeds – Panama",
    type: "sativa",
    genetics: "100% Sativa",
    plantType: "photo",
    floweringDays: 75,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Reine panamaische Landrasse. Tropische Sativa mit süßem, erdigem Profil. Langer, langsamer Grow mit authentischem Ergebnis.",
    aroma: "Süß, tropisch, erdig",
    effect: "Klar, energisch, meditativ",
  },
  {
    name: "Neville's Haze",
    type: "sativa",
    genetics: "85% Sativa / 15% Indica",
    plantType: "photo",
    floweringDays: 85,
    difficulty: "schwer",
    yieldIndoor: "300–400g/m²",
    thc: "20–24%",
    cbd: "<1%",
    description: "Haze x Northern Lights. Von Neville Schoenmakers legendärem Seed Stock. Eine der besten Haze-Varianten.",
    aroma: "Citrus, würzig, erdig",
    effect: "Stark euphorisch, kreativ, langanhaltend",
  },
  {
    name: "Mazar-I-Sharif",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "photo",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Afghanische Landrasse mit sativa-dominanten Eigenschaften. Aus der Region Mazar-i-Sharif. Selten und besonders.",
    aroma: "Würzig, süß, blumig",
    effect: "Klar, entspannend, kreativ",
  },
  {
    name: "Super Silver Haze",
    type: "sativa",
    genetics: "80% Sativa / 20% Indica",
    plantType: "photo",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Skunk #1 x Northern Lights x Haze. Mehrfacher High Times Cannabis Cup Gewinner. Berühmt für trichombedeckte Buds.",
    aroma: "Würzig, erdig, citrus",
    effect: "Energisch, euphorisch, kreativ",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // HYBRID
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "White Widow",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Klassischer niederländischer Hybrid aus Brazilian Sativa x South Indian Indica. Bekannt für harzige Buds und zuverlässigen Ertrag. Cannabis Cup Legende.",
    aroma: "Erdig, holzig, leicht süß",
    effect: "Ausgewogen, kreativ, entspannend",
  },
  {
    name: "OG Kush",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "US-Westküsten-Klassiker. Chemdog x Lemon Thai x Hindu Kush. Komplexes Terpenprofil, starker Effekt. Eine der einflussreichsten Sorten der modernen Cannabis-Zucht.",
    aroma: "Diesel, pine, erdig",
    effect: "Euphorisch, entspannend, hungeranregend",
  },
  {
    name: "Gorilla Glue #4 (GG4)",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "450–550g/m²",
    thc: "24–28%",
    cbd: "<1%",
    description: "Chem's Sister x Sour Dubb x Chocolate Diesel. Extrem harzige Buds, bekannt für starke Klebrigkeit ('Glue'). Cup-Gewinner.",
    aroma: "Diesel, erdig, pine",
    effect: "Stark, entspannend, euphorisch",
  },
  {
    name: "Girl Scout Cookies (GSC)",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 63,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–28%",
    cbd: "<1%",
    description: "OG Kush x Durban Poison. Eine der einflussreichsten modernen Sorten. Mutterpflanze vieler neuer Sorten (Gelato, Thin Mint, etc.).",
    aroma: "Süß, erdig, leicht minzig",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Gelato",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 56,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Sunset Sherbet x Thin Mint GSC. Berühmte 'Dessert'-Sorte aus Kalifornien. Wunderschöne lila-grüne Buds mit cremigem Aroma.",
    aroma: "Süß, cremig, beerig, citrus",
    effect: "Entspannend, euphorisch, kreativ",
  },
  {
    name: "Blue Dream",
    type: "hybrid",
    genetics: "60% Sativa / 40% Indica",
    plantType: "photo",
    floweringDays: 63,
    difficulty: "leicht",
    yieldIndoor: "450–550g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Blueberry Indica x Sativa Haze. Eine der meistverkauften Sorten in Kalifornien. Ausgewogenes High, hoher Ertrag, anfängerfreundlich.",
    aroma: "Blaubeere, süß, vanille",
    effect: "Ausgewogen, euphorisch, kreativ, entspannend",
  },
  {
    name: "Wedding Cake",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 56,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "22–27%",
    cbd: "<1%",
    description: "Triangle Kush x Animal Mints. Beliebter moderner Hybrid mit süßem, kuchenartigem Aroma. Dichte, frostige Buds.",
    aroma: "Süß, vanille, erdig, pfeffrig",
    effect: "Entspannend, euphorisch, appetitanregend",
  },
  {
    name: "Runtz",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 65,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "22–29%",
    cbd: "<1%",
    description: "Zkittlez x Gelato. Eine der beliebtesten modernen Sorten. Extrem süßes Candy-Aroma, starke Potenz.",
    aroma: "Süß, fruchtig, candy, beerig",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Zkittlez",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–23%",
    cbd: "<1%",
    description: "Grape Ape x Grapefruit x undisclosed. Bekannt für ihr extremes Candy-Aroma. Cannabis Cup Gewinner.",
    aroma: "Süß, fruchtig, Traube, Beeren",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "Grape Ape",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Afghani x Skunk. Benannt nach dem intensiven Trauben-Aroma. Robust und einfach zu growen.",
    aroma: "Traube, süß, beerig",
    effect: "Entspannend, euphorisch, körperlich",
  },
  {
    name: "Chemdog 91",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 65,
    difficulty: "schwer",
    yieldIndoor: "300–400g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Legendäre Mutter-Sorte. Ursprung vieler berühmter Sorten (OG Kush, Sour Diesel, etc.). Intensives Diesel-Aroma.",
    aroma: "Diesel, chemisch, erdig",
    effect: "Stark, euphorisch, langanhaltend",
  },
  {
    name: "Headband",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "OG Kush x Sour Diesel. Benannt nach dem 'Druck'-Gefühl auf der Stirn. Stark und langanhaltend.",
    aroma: "Diesel, citrus, erdig",
    effect: "Euphorisch, entspannend, 'kopf-drückend'",
  },
  {
    name: "Pineapple Express",
    type: "hybrid",
    genetics: "60% Sativa / 40% Indica",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Trainwreck x Hawaiian. Berühmt durch den gleichnamigen Film. Tropisches Aroma, ausgewogenes High.",
    aroma: "Ananas, tropisch, süß, cedar",
    effect: "Energisch, euphorisch, fokussierend",
  },
  {
    name: "Trainwreck",
    type: "hybrid",
    genetics: "60% Sativa / 40% Indica",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–25%",
    cbd: "<1%",
    description: "Mexican x Thai x Afghani. Unberechenbares Wachstum ('Trainwreck'), aber lohnenswert. Schnelle Blüte, hoher Ertrag.",
    aroma: "Citrus, erdig, würzig",
    effect: "Energisch, euphorisch, kreativ",
  },
  {
    name: "Blueberry",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "DJ Short's legendäre Kreuzung. Eine der ersten 'Dessert'-Sorten. Wunderschöne lila Färbung, intensives Blaubeer-Aroma.",
    aroma: "Blaubeere, süß, beerig",
    effect: "Entspannend, euphorisch, kreativ",
  },
  {
    name: "Skunk #1",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Afghani x Mexican x Colombian. Die Urmutter der modernen Cannabis-Zucht. Seit den 70ern kultiviert. Extrem stabil und zuverlässig.",
    aroma: "Skunk, süß, erdig",
    effect: "Ausgewogen, entspannend, glücklich",
  },
  {
    name: "AK-47",
    type: "hybrid",
    genetics: "65% Sativa / 35% Indica",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Colombian x Mexican x Thai x Afghani. Trotz des aggressiven Namens ein sanftes, langanhaltendes High. Mehrfacher Cup-Gewinner.",
    aroma: "Erdig, süß, blumig",
    effect: "Entspannend, euphorisch, langanhaltend",
  },
  {
    name: "White Russian",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "400–500g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "White Widow x AK-47. Mehrfacher Cannabis Cup Gewinner. Sehr harzreich, starker Effekt.",
    aroma: "Süß, erdig, pine",
    effect: "Stark entspannend, euphorisch",
  },
  {
    name: "Super Skunk",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "leicht",
    yieldIndoor: "450–550g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Skunk #1 x Afghani. Eine der zuverlässigsten Sorten überhaupt. Schnell, einfach, hoher Ertrag. Ideal für Anfänger und SOG.",
    aroma: "Skunk, süß, citrus",
    effect: "Entspannend, euphorisch, körperlich",
  },
  {
    name: "Big Bud",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 50,
    difficulty: "leicht",
    yieldIndoor: "500–600g/m²",
    thc: "15–18%",
    cbd: "<1%",
    description: "Skunk x Afghani. Wie der Name sagt: Enorme Buds. Eine der ertragreichsten Sorten. Perfekt für kommerzielle Züchter.",
    aroma: "Süß, erdig, blumig",
    effect: "Entspannend, mild, körperlich",
  },
  {
    name: "Bubble Gum",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "15–20%",
    cbd: "<1%",
    description: "Indiana Bubble Gum x mehrere Hybriden. Süßes Kaugummi-Aroma. Mehrfacher Cannabis Cup Gewinner.",
    aroma: "Kaugummi, süß, erdig",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "Biscotti",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "22–28%",
    cbd: "<1%",
    description: "Gelato 25 x Forum Cut GSC. Moderne Premium-Sorte. Extrem harzreich, komplexes Terpenprofil.",
    aroma: "Süß, nussig, erdig, vanille",
    effect: "Entspannend, euphorisch, stark",
  },
  {
    name: "Mac (Miracle Alien Cookies)",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "22–26%",
    cbd: "<1%",
    description: "Alien Cookies x Starfighter. Eine der gefragtesten modernen Sorten. Extrem frostige Buds.",
    aroma: "Süß, erdig, citrus, blumig",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Purple Panda",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Moderne Kreuzung mit wunderschönen lila Buds. Süßes, beeriges Aroma.",
    aroma: "Beeren, süß, erdig",
    effect: "Entspannend, euphorisch, körperlich",
  },
  {
    name: "Tropicana Cookies",
    type: "hybrid",
    genetics: "55% Sativa / 45% Indica",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "22–28%",
    cbd: "<1%",
    description: "Girl Scout Cookies x Tangie. Tropischer Cookie-Hybrid. Cannabis Cup Gewinner.",
    aroma: "Orange, citrus, süß, erdig",
    effect: "Euphorisch, kreativ, entspannend",
  },
  {
    name: "Forbidden Fruit",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "22–27%",
    cbd: "<1%",
    description: "Cherry Pie x Big Bud. Süßes Kirsch-Aroma, dichte Buds. Beliebte moderne Sorte.",
    aroma: "Kirsche, süß, erdig",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "London Pound Cake",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "Sunset Sherbet x Unknown. Premium-Dessert-Sorte mit unglaublichem Terpenprofil.",
    aroma: "Süß, cremig, beerig, vanille",
    effect: "Entspannend, euphorisch, stark",
  },
  {
    name: "Snow Caps",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "PT White x Hawaiian Snow. Extrem frostige Buds, ausgewogener Effekt.",
    aroma: "Erdig, pine, leicht citrus",
    effect: "Ausgewogen, euphorisch, kreativ",
  },
  {
    name: "Kush Mints",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "22–28%",
    cbd: "<1%",
    description: "Biscotti x Animal Mints. Moderne Premium-Sorte mit minzig-kusigem Profil.",
    aroma: "Minzig, erdig, süß, pfeffrig",
    effect: "Entspannend, euphorisch, fokussierend",
  },
  {
    name: "Jet Fuel",
    type: "hybrid",
    genetics: "55% Sativa / 45% Indica",
    plantType: "photo",
    floweringDays: 60,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "Aspen OG x Chemdog 45. Starkes Diesel-Aroma, hohe Potenz. Beliebt bei Kennern.",
    aroma: "Diesel, chemisch, erdig",
    effect: "Energisch, euphorisch, fokussierend",
  },
  {
    name: "Lemon Tree",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "photo",
    floweringDays: 55,
    difficulty: "mittel",
    yieldIndoor: "400–500g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "Lemon Skunk x Sour OG. Intensives Zitronen-Aroma mit erdigen Untertönen.",
    aroma: "Zitrone, citrus, erdig, diesel",
    effect: "Entspannend, euphorisch, kreativ",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // AUTOFLOWER – INDICA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Northern Lights Auto",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Autoflower-Version der legendären Northern Lights. Schnell und einfach. Von Samen bis Ernte in ~70 Tagen.",
    aroma: "Süß, pine, würzig",
    effect: "Entspannend, körperlich, mild",
  },
  {
    name: "Blueberry Auto",
    type: "indica",
    genetics: "80% Indica / 20% Sativa",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Süßer Beerengeschmack in einer einfach zu growenden Autoflower. Wunderschöne lila Färbung möglich.",
    aroma: "Blaubeere, süß, fruchtig",
    effect: "Entspannend, glücklich, leicht körperlich",
  },
  {
    name: "Critical Auto",
    type: "indica",
    genetics: "70% Indica / 30% Sativa",
    plantType: "auto",
    floweringDays: 60,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "1–2%",
    description: "Autoflower-Version der Critical Mass. Extrem schnell, hoher Ertrag für eine Auto. Ideal für mehrere Durchgänge pro Jahr.",
    aroma: "Süß, erdig, skunk",
    effect: "Entspannend, körperlich, mild",
  },
  {
    name: "Bubble Gum Auto",
    type: "indica",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "15–18%",
    cbd: "<1%",
    description: "Kaugummi-Aroma in einer schnellen Autoflower. Einfach zu growen, zuverlässig.",
    aroma: "Kaugummi, süß, erdig",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "Hindu Kush Auto",
    type: "indica",
    genetics: "90% Indica / 10% Sativa",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "17–21%",
    cbd: "<1%",
    description: "Autoflower-Version der reinen afghanischen Landrasse. Kompakt, harzreich, einfach.",
    aroma: "Erdig, süß, sandelholz",
    effect: "Tief entspannend, sedierend",
  },
  {
    name: "Gelato Auto",
    type: "indica",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Gelato in Autoflower-Form. Cremiges Dessert-Aroma, frostige Buds. Schnellere Alternative zum Photo-Original.",
    aroma: "Süß, cremig, beerig",
    effect: "Entspannend, euphorisch, kreativ",
  },
  {
    name: "Wedding Cake Auto",
    type: "indica",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–24%",
    cbd: "<1%",
    description: "Wedding Cake als Autoflower. Süßes Vanille-Aroma, dichte Buds, starke Potenz in kurzer Zeit.",
    aroma: "Süß, vanille, erdig",
    effect: "Entspannend, euphorisch, stark",
  },
  {
    name: "Gorilla Glue Auto",
    type: "indica",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "20–25%",
    cbd: "<1%",
    description: "GG4 als Autoflower. Extrem harzig, starke Klebrigkeit. Hohe Potenz in ~70 Tagen.",
    aroma: "Diesel, erdig, pine",
    effect: "Stark entspannend, euphorisch",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // AUTOFLOWER – SATIVA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "Amnesia Haze Auto",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "auto",
    floweringDays: 75,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Amnesia Haze als Autoflower. Etwas längere Blüte als andere Autos, aber echtes Haze-High.",
    aroma: "Citrus, erdig, scharf",
    effect: "Energisch, euphorisch, kreativ",
  },
  {
    name: "Jack Herer Auto",
    type: "sativa",
    genetics: "55% Sativa / 45% Indica",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Jack Herer als Autoflower. Würzig-kreatives Haze-High in Auto-Form. Kompakte Pflanze.",
    aroma: "Würzig, pine, citrus",
    effect: "Klar, kreativ, euphorisch",
  },
  {
    name: "Sour Diesel Auto",
    type: "sativa",
    genetics: "65% Sativa / 35% Indica",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Sour Diesel als Autoflower. Diesel-Aroma bleibt erhalten, etwas kompakter als das Photo-Original.",
    aroma: "Diesel, citrus, erdig",
    effect: "Energisch, euphorisch, fokussierend",
  },
  {
    name: "Super Lemon Haze Auto",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Super Lemon Haze als Autoflower. Intensive Zitrone, Cup-würdig auch als Auto.",
    aroma: "Zitrone, citrus, süß",
    effect: "Energisch, euphorisch, kreativ",
  },
  {
    name: "Green Crack Auto",
    type: "sativa",
    genetics: "70% Sativa / 30% Indica",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Green Crack als Autoflower. Schnelles tropisches Sativa-High in Auto-Form.",
    aroma: "Mango, citrus, tropisch",
    effect: "Energisch, fokussierend, glücklich",
  },
  {
    name: "Durban Poison Auto",
    type: "sativa",
    genetics: "80% Sativa / 20% Indica",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Die reine südafrikanische Sativa als Autoflower. Selten und besonders – echtes Landrassen-High in Auto-Form.",
    aroma: "Süß, erdig, anis, pine",
    effect: "Energisch, klar, motivierend",
  },
  // ═══════════════════════════════════════════════════════════════════════════
  // AUTOFLOWER – HYBRID
  // ═══════════════════════════════════════════════════════════════════════════
  {
    name: "White Widow Auto",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "White Widow als Autoflower. Harzige Buds, ausgewogenes High, einfach zu growen.",
    aroma: "Erdig, holzig, süß",
    effect: "Ausgewogen, entspannend, kreativ",
  },
  {
    name: "OG Kush Auto",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "OG Kush als Autoflower. Diesel-Pine-Aroma bleibt erhalten. Kompaktere Pflanze als das Original.",
    aroma: "Diesel, pine, erdig",
    effect: "Euphorisch, entspannend",
  },
  {
    name: "Girl Scout Cookies Auto",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "GSC als Autoflower. Süßes Cookie-Aroma, starke Potenz. Braucht etwas länger als andere Autos.",
    aroma: "Süß, erdig, minzig",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Runtz Auto",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Runtz als Autoflower. Extrem süßes Candy-Aroma. Eine der besten modernen Autos.",
    aroma: "Süß, fruchtig, candy",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Zkittlez Auto",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Zkittlez als Autoflower. Fruchtiges Candy-Aroma, einfach zu growen. Schöne lila Färbung möglich.",
    aroma: "Süß, fruchtig, Traube",
    effect: "Entspannend, euphorisch, glücklich",
  },
  {
    name: "Blue Dream Auto",
    type: "hybrid",
    genetics: "55% Sativa / 45% Indica",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Blue Dream als Autoflower. Ausgewogenes High, hoher Ertrag für eine Auto. Blaubeer-Aroma.",
    aroma: "Blaubeere, süß, vanille",
    effect: "Ausgewogen, euphorisch, kreativ",
  },
  {
    name: "Pineapple Express Auto",
    type: "hybrid",
    genetics: "55% Sativa / 45% Indica",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "16–20%",
    cbd: "<1%",
    description: "Pineapple Express als Autoflower. Tropisches Aroma, filmberühmt. Schnell und einfach.",
    aroma: "Ananas, tropisch, süß",
    effect: "Energisch, euphorisch, fokussierend",
  },
  {
    name: "AK-47 Auto",
    type: "hybrid",
    genetics: "60% Sativa / 40% Indica",
    plantType: "auto",
    floweringDays: 65,
    difficulty: "leicht",
    yieldIndoor: "300–400g/m²",
    thc: "15–18%",
    cbd: "<1%",
    description: "AK-47 als Autoflower. Zuverlässig, einfach, langanhaltendes High. Gut für Anfänger.",
    aroma: "Erdig, süß, blumig",
    effect: "Entspannend, euphorisch, langanhaltend",
  },
  {
    name: "Mac Auto",
    type: "hybrid",
    genetics: "50% Indica / 50% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Miracle Alien Cookies als Autoflower. Extrem frostige Buds, Premium-Qualität in Auto-Form.",
    aroma: "Süß, erdig, citrus",
    effect: "Euphorisch, entspannend, kreativ",
  },
  {
    name: "Biscotti Auto",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Biscotti als Autoflower. Nussig-süßes Aroma, extrem harzig. Premium-Dessert-Sorte.",
    aroma: "Süß, nussig, erdig",
    effect: "Entspannend, euphorisch, stark",
  },
  {
    name: "Do-Si-Dos Auto",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–24%",
    cbd: "<1%",
    description: "Do-Si-Dos als Autoflower. Starke Indica-Potenz in Auto-Form. Wunderschöne lila Buds.",
    aroma: "Süß, erdig, blumig",
    effect: "Stark entspannend, sedierend",
  },
  {
    name: "GMO Auto",
    type: "hybrid",
    genetics: "60% Indica / 40% Sativa",
    plantType: "auto",
    floweringDays: 75,
    difficulty: "schwer",
    yieldIndoor: "250–350g/m²",
    thc: "20–26%",
    cbd: "<1%",
    description: "GMO als Autoflower. Intensives Knoblauch-Aroma, extreme Potenz. Für erfahrene Grower die das Besondere suchen.",
    aroma: "Knoblauch, erdig, diesel",
    effect: "Stark sedierend, intensiv",
  },
  {
    name: "Wedding Cake Auto Fast",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 60,
    difficulty: "leicht",
    yieldIndoor: "350–450g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Schnelle Wedding-Cake-Auto-Variante. Nur 60 Tage von Samen bis Ernte. Süßes Vanille-Aroma.",
    aroma: "Süß, vanille, pfeffrig",
    effect: "Entspannend, euphorisch",
  },
  {
    name: "Gelato 41 Auto",
    type: "hybrid",
    genetics: "55% Indica / 45% Sativa",
    plantType: "auto",
    floweringDays: 70,
    difficulty: "mittel",
    yieldIndoor: "300–400g/m²",
    thc: "18–22%",
    cbd: "<1%",
    description: "Gelato #41 als Autoflower. Die berühmteste Gelato-Phänotyp als Auto. Cremig-süß.",
    aroma: "Cremig, süß, beerig, citrus",
    effect: "Entspannend, euphorisch, kreativ",
  },
];
