import { useState } from "react";

export default function AirExchangeCalculatorPage() {
  const [tentWidth, setTentWidth] = useState(100); // cm
  const [tentDepth, setTentDepth] = useState(100); // cm
  const [tentHeight, setTentHeight] = useState(200); // cm
  const [lightWattage, setLightWattage] = useState(400); // W
  const [ambientTemp, setAmbientTemp] = useState(25); // °C
  const [targetTemp, setTargetTemp] = useState(26); // °C

  // Calculate tent volume in m³
  const tentVolume = (tentWidth * tentDepth * tentHeight) / 1000000;

  // Heat generated by light (roughly 70% of wattage becomes heat)
  const heatWatts = lightWattage * 0.7;

  // Required air exchange rate
  // Rule of thumb: 1 air change per minute for LED, 2 for HPS
  // Adjusted for temperature difference
  const tempDiff = targetTemp - ambientTemp;
  const baseAirChanges = lightWattage > 300 ? 2 : 1.5; // air changes per minute
  
  // Adjust for temperature difference
  const tempFactor = Math.max(1, 1 + (tempDiff / 10));
  const airChangesPerMinute = baseAirChanges * tempFactor;

  // Required fan capacity in m³/h
  const requiredM3PerH = tentVolume * airChangesPerMinute * 60;

  // Recommended fan size (with 25% safety margin)
  const recommendedFanSize = requiredM3PerH * 1.25;

  // Carbon filter (should handle 25% more than fan)
  const carbonFilterSize = recommendedFanSize * 1.25;

  // Intake fan (70% of exhaust)
  const intakeFanSize = recommendedFanSize * 0.7;

  // Duct diameter recommendations
  const getDuctDiameter = (m3h: number) => {
    if (m3h < 200) return 100;
    if (m3h < 400) return 125;
    if (m3h < 600) return 150;
    return 200;
  };

  const exhaustDuct = getDuctDiameter(recommendedFanSize);
  const intakeDuct = getDuctDiameter(intakeFanSize);

  return (
    <div className="page">
      <h1>Luftaustausch-Rechner</h1>
      <p className="subtitle">Berechne die benötigte Lüfterleistung für dein Zelt</p>

      <div className="card">
        <h3>Zelt-Maße</h3>
        <div className="form-row">
          <div className="form-group">
            <label>Breite (cm)</label>
            <input
              type="number"
              step="10"
              min="0"
              value={tentWidth}
              onChange={(e) => setTentWidth(parseFloat(e.target.value) || 0)}
            />
          </div>
          <div className="form-group">
            <label>Tiefe (cm)</label>
            <input
              type="number"
              step="10"
              min="0"
              value={tentDepth}
              onChange={(e) => setTentDepth(parseFloat(e.target.value) || 0)}
            />
          </div>
          <div className="form-group">
            <label>Höhe (cm)</label>
            <input
              type="number"
              step="10"
              min="0"
              value={tentHeight}
              onChange={(e) => setTentHeight(parseFloat(e.target.value) || 0)}
            />
          </div>
        </div>

        <div className="form-group">
          <label>Lampenleistung (W)</label>
          <input
            type="number"
            step="50"
            min="0"
            value={lightWattage}
            onChange={(e) => setLightWattage(parseFloat(e.target.value) || 0)}
          />
        </div>

        <div className="form-row">
          <div className="form-group">
            <label>Ambiente-Temp (°C)</label>
            <input
              type="number"
              step="1"
              min="0"
              max="50"
              value={ambientTemp}
              onChange={(e) => setAmbientTemp(parseFloat(e.target.value) || 0)}
            />
          </div>
          <div className="form-group">
            <label>Ziel-Temp (°C)</label>
            <input
              type="number"
              step="1"
              min="0"
              max="50"
              value={targetTemp}
              onChange={(e) => setTargetTemp(parseFloat(e.target.value) || 0)}
            />
          </div>
        </div>
      </div>

      <div className="card result-card">
        <h3>Zelt-Volumen</h3>
        <div className="result">
          <div className="result-item large">
            <span className="value highlight">{tentVolume.toFixed(2)} m³</span>
          </div>
        </div>
      </div>

      <div className="card result-card">
        <h3>Benötigte Lüfterleistung</h3>
        <div className="result">
          <div className="result-item">
            <span className="label">Wärme durch Lampe:</span>
            <span className="value">{heatWatts.toFixed(0)} W</span>
          </div>
          <div className="result-item">
            <span className="label">Luftwechsel/min:</span>
            <span className="value">{airChangesPerMinute.toFixed(1)}</span>
          </div>
          <div className="result-item">
            <span className="label">Mindestanforderung:</span>
            <span className="value">{requiredM3PerH.toFixed(0)} m³/h</span>
          </div>
        </div>
      </div>

      <div className="card result-card">
        <h3>Empfohlene Komponenten</h3>
        <div className="result">
          <div className="result-item">
            <span className="label">Abluft (mit 25% Reserve):</span>
            <span className="value highlight">{recommendedFanSize.toFixed(0)} m³/h</span>
          </div>
          <div className="result-item">
            <span className="label">Aktivkohlefilter:</span>
            <span className="value">{carbonFilterSize.toFixed(0)} m³/h</span>
          </div>
          <div className="result-item">
            <span className="label">Zuluft (70% von Abluft):</span>
            <span className="value">{intakeFanSize.toFixed(0)} m³/h</span>
          </div>
        </div>

        <div className="result-divider"></div>

        <div className="result">
          <div className="result-item">
            <span className="label">Abluft-Schlauch:</span>
            <span className="value">Ø {exhaustDuct} mm</span>
          </div>
          <div className="result-item">
            <span className="label">Zuluft-Schlauch:</span>
            <span className="value">Ø {intakeDuct} mm</span>
          </div>
        </div>

        <div className="info-box">
          <strong>💡 Tipps:</strong>
          <ul>
            <li>Verwende einen dimmbaren Abluftventilator für bessere Kontrolle</li>
            <li>Der Aktivkohlefilter sollte immer größer dimensioniert sein als der Ventilator</li>
            <li>Bei heißen Sommern: Plane 20-30% mehr Reserve ein</li>
            <li>Vermeide zu viele Kurven im Schlauch (erhöht den Widerstand)</li>
          </ul>
        </div>
      </div>

      <div className="card">
        <h3>📊 Richtwerte für Zeltgrößen</h3>
        <table className="info-table">
          <thead>
            <tr>
              <th>Zelt</th>
              <th>Volumen</th>
              <th>Empfohlener Abluft</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>60x60x120</td>
              <td>0.43 m³</td>
              <td>~150 m³/h</td>
            </tr>
            <tr>
              <td>80x80x160</td>
              <td>1.02 m³</td>
              <td>~250 m³/h</td>
            </tr>
            <tr>
              <td>100x100x200</td>
              <td>2.00 m³</td>
              <td>~400 m³/h</td>
            </tr>
            <tr>
              <td>120x120x200</td>
              <td>2.88 m³</td>
              <td>~500 m³/h</td>
            </tr>
            <tr>
              <td>150x150x200</td>
              <td>4.50 m³</td>
              <td>~750 m³/h</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  );
}
